name: Run Shell Script

on:
  push:
    branches:
      - main  # change to your working branch if needed

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run myscript.sh
        run: bash ./myscript.sh
